GENDER_CHOICES = [
    ("M", "Male"),
    ("F", "Female"),
    ("O", "Other"),
]

CURRENCY_CHOICES = [
    ("EU", "Euro"),
    ("RUS", "Dollar"),
]

COUNTRY_CHOICES = [
    ("AL", "Albania"),
    ("AD", "Andorra"),
    ("AT", "Austria"),
    ("BY", "Belarus"),
    ("BE", "Belgium"),
    ("BA", "Bosnia and Herzegovina"),
    ("BG", "Bulgaria"),
    ("HR", "Croatia"),
    ("CY", "Cyprus"),
    ("CZ", "Czech Republic"),
    ("DK", "Denmark"),
    ("EE", "Estonia"),
    ("FI", "Finland"),
    ("FR", "France"),
    ("DE", "Germany"),
    ("GR", "Greece"),
    ("HU", "Hungary"),
    ("IS", "Iceland"),
    ("IE", "Ireland"),
    ("IT", "Italy"),
    ("LV", "Latvia"),
    ("LI", "Liechtenstein"),
    ("LT", "Lithuania"),
    ("LU", "Luxembourg"),
    ("MT", "Malta"),
    ("MD", "Moldova"),
    ("MC", "Monaco"),
    ("ME", "Montenegro"),
    ("NL", "Netherlands"),
    ("MK", "North Macedonia"),
    ("NO", "Norway"),
    ("PL", "Poland"),
    ("PT", "Portugal"),
    ("RO", "Romania"),
    ("RU", "Russia"),
    ("RS", "Serbia"),
    ("SK", "Slovakia"),
    ("SI", "Slovenia"),
    ("ES", "Spain"),
    ("SE", "Sweden"),
    ("CH", "Switzerland"),
    ("UA", "Ukraine"),
    ("GB", "United Kingdom"),
    ("KZ", "Kazakhstan"),
]
