# Generated by Django 5.2.1 on 2025-05-26 18:42

import autoslug.fields
import django.db.models.deletion
import hotels.models.images
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='private, sand, stone..', max_length=256)),
                ('distance_hotel', models.CharField(help_text='250 mt to hotel', max_length=256)),
                ('image', models.ImageField(upload_to='beach_images')),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Beach',
                'verbose_name_plural': 'Beach',
                'db_table': 'beach',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='adults only, familiy friendly', max_length=256)),
                ('description', models.TextField(max_length=2000)),
                ('image', models.ImageField(upload_to='cat_images')),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='FoodBevarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='lobby bar, italyan restoran, ana rest.', max_length=256)),
                ('is_free', models.BooleanField(default=True, help_text='ücretliyse false yap!')),
                ('image', models.ImageField(height_field='500', upload_to='foodbevarages', width_field='700')),
            ],
            options={
                'verbose_name': 'Food & Bevarage',
                'verbose_name_plural': 'Food & Bevarages',
                'db_table': 'food_bevarage',
            },
        ),
        migrations.CreateModel(
            name='GeneralFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='pool, spa, gym', max_length=256)),
                ('is_free', models.BooleanField(default=True, help_text='ücretliyse false yap!')),
                ('image', models.ImageField(height_field='500', upload_to='general_facility', width_field='700')),
            ],
            options={
                'verbose_name': 'General Facility',
                'verbose_name_plural': 'General Facilities',
                'db_table': 'general_facility',
            },
        ),
        migrations.CreateModel(
            name='LocationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_map_url', models.URLField(help_text='http://map.google.com/en-boy', max_length=1000)),
                ('zip_code', models.CharField(help_text='07330', max_length=7)),
                ('to_airport', models.CharField(help_text='70 km', max_length=64)),
                ('to_beach', models.CharField(help_text='500 mt', max_length=64)),
                ('to_bus_station', models.CharField(help_text='200 mt', max_length=64)),
                ('to_city_center', models.CharField(help_text='5 km', max_length=64)),
            ],
            options={
                'verbose_name': 'Location Detail',
                'verbose_name_plural': 'Location Details',
                'db_table': 'location_details',
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='full, partial refund', max_length=256)),
                ('description', models.TextField(max_length=2000)),
                ('before_check_in', models.PositiveIntegerField(default=0, help_text='girişten kaç gün öncesine kadar?')),
                ('cancellation_fee', models.PositiveIntegerField(default=0, max_length=100)),
            ],
            options={
                'verbose_name': 'Penalty',
                'verbose_name_plural': 'Penalties',
                'db_table': 'penalty',
            },
        ),
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='all inklusive, bed&breakfast,..', max_length=256)),
                ('description', models.TextField(help_text='24 saat herşey dahil hizmeet, import içecekler de dahil', max_length=1256)),
            ],
            options={
                'verbose_name': 'Pension',
                'verbose_name_plural': 'Pensions',
                'db_table': 'pension',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='check-in 14:00', max_length=256)),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'db_table': 'policies',
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='indoor, outdoor, children etc.', max_length=256)),
                ('image', models.ImageField(height_field='500', upload_to='pools', width_field='700')),
                ('opening_time', models.CharField(help_text='09:00', max_length=5)),
                ('closing_time', models.CharField(help_text='19:00', max_length=5)),
            ],
            options={
                'verbose_name': 'Pool',
                'verbose_name_plural': 'Pools',
                'db_table': 'pools',
            },
        ),
        migrations.CreateModel(
            name='RoomFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='TV, air-conditioning', max_length=256)),
            ],
            options={
                'verbose_name': 'Room Facility',
                'verbose_name_plural': 'Room Facilities',
                'db_table': 'room_facility',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('description', models.TextField(max_length=2000)),
                ('thumbnail', models.ImageField(upload_to='hotel_thumbnail')),
                ('stars', models.CharField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')])),
                ('child_age_end', models.SmallIntegerField(default=12, help_text='Kaç yaşına kadar çocuk indirimi varsa')),
                ('reviews_frame', models.CharField(max_length=1000)),
                ('category', models.ManyToManyField(to='hotels.category')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotel_destination', to='destinations.destinationmodel')),
                ('facilities', models.ManyToManyField(help_text='spa, asansör, pool', to='hotels.generalfacility')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotels.locationdetails')),
                ('policies', models.ManyToManyField(help_text='+16 only, no single man', to='hotels.policy')),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to=hotels.models.images.hotel_image_upload_path)),
                ('alt_text', models.CharField(blank=True, max_length=256, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_images', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='Sea view, Mountain view', max_length=256)),
                ('short_description', models.CharField(help_text='twin beds, queen bed', max_length=256)),
                ('single_supplement', models.PositiveIntegerField(default=50, help_text='kişi başı gecelik pp fiyata + %single supplement uygulanır, pp 100 ise 150 gibi.')),
                ('triple_supplement', models.PositiveIntegerField(default=30, help_text='(kişi başı gecelik fiyat * 2) + (kişi başı gecelik fiyat / 100 * (100 - triple_supplement))')),
                ('family_supplement', models.PositiveIntegerField(default=3, help_text='kişi başı gecelik fiyat * family_supplement')),
                ('cancellation_penalty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roompenalty', to='hotels.penalty')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotelrooms', to='hotels.hotel')),
                ('pansion', models.ManyToManyField(help_text='all inclusive', to='hotels.pension')),
                ('policies', models.ManyToManyField(to='hotels.policy')),
                ('facilities', models.ManyToManyField(help_text='minibar', to='hotels.roomfacilities')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImageModel',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to=hotels.models.images.room_image_upload_path)),
                ('alt_text', models.CharField(blank=True, max_length=256, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='hotels.room')),
            ],
            options={
                'verbose_name': 'Room Image',
                'verbose_name_plural': 'Room Images',
                'db_table': 'room_images',
            },
        ),
    ]
