# Generated by Django 5.2.1 on 2025-05-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalfacility',
            name='image',
            field=models.ImageField(upload_to='general_facility'),
        ),
    ]
