# Generated by Django 5.2.1 on 2025-05-27 20:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotel_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodPricing',
            fields=[
                ('period_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='sea view', max_length=256)),
                ('description', models.TextField(help_text='sea view with twin beds', max_length=2000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('currency', models.CharField(choices=[('EUR', 'EUR'), ('GBP', 'GBP'), ('USD', 'USD')], default='EUR')),
                ('pp_net_price', models.DecimalField(decimal_places=2, default=0.0, help_text='per person gecelik net fiyat', max_digits=6)),
                ('pp_retail_price', models.DecimalField(decimal_places=2, default=0.0, help_text='per person gecelik satış fiyatı', max_digits=6)),
                ('discount_rate', models.PositiveIntegerField(blank=True, help_text='indirim oranı tüm katılımcıların toplam rezervasyon tutarında yüzdelik olarak düşülücek.', null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_periods', to='hotels.room')),
            ],
            options={
                'verbose_name': 'Period Pricing',
                'verbose_name_plural': 'PeriodS PricingS',
                'db_table': 'periods',
            },
        ),
        migrations.CreateModel(
            name='BlockDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_date', models.DateField()),
                ('period_pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_blokdates', to='hotels.periodpricing')),
            ],
            options={
                'verbose_name': 'Blocked Date',
                'verbose_name_plural': 'Blocked Dates',
                'db_table': 'blocked_dates',
            },
        ),
    ]
