# Generated by Django 5.2.1 on 2025-05-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_periodpricing_blockdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='cancellation_fee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
